#!/bin/bash 

# CERIT Scientific Cloud, 2013
# based on scripts from one:src/vmm_mad/remotes/kvm/
#   Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)
#   Licensed under the Apache License, Version 2.0

source $(dirname $0)/rhcsrc
source $(dirname $0)/../../scripts_common.sh

deploy_id=$1

exec_and_log "$RHCS_CLUSVCADM -R vm:$deploy_id" \
    "Could not restart domain $deploy_id"

exit 0
